# Generated by Django 4.2.4 on 2023-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuser',
            old_name='has_key',
            new_name='has_castle_key',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='has_forge_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='has_merchant_key',
            field=models.BooleanField(default=False),
        ),
    ]
