# Generated by Django 4.2.4 on 2023-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_rename_has_key_gameuser_has_castle_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuser',
            old_name='has_castle_key',
            new_name='has_fisherman_key',
        ),
        migrations.RenameField(
            model_name='gameuser',
            old_name='has_merchant_key',
            new_name='has_greenhouse_key',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='has_kitchen_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='has_loft_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='has_stones_key',
            field=models.BooleanField(default=False),
        ),
    ]
