# Generated by Django 4.2.4 on 2023-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_rename_has_castle_key_gameuser_has_fisherman_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='day_two',
            field=models.BooleanField(default=False),
        ),
    ]
