# Generated by Django 4.2.4 on 2023-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_gameuser_day_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='day_three',
            field=models.BooleanField(default=False),
        ),
    ]
