# Generated by Django 4.2.4 on 2023-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_gameuser_day_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
